# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: centro.estudiantes.esis@gmail.com
GMAIL_PASSWORD: esisunjbg2013
ADMIN_NAME: Tony
ADMIN_EMAIL: centro.estudiantes.esis@gmail.com
ADMIN_PASSWORD: esisunjbg2013
ROLES: [admin, usuario, VIP]
